excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://beingRohitashva.github.io
title: beingRohitashva
tagline: A log of everyday life
description: want to enhance my tiny knowledge by Blogging @tinypress.
paginate: 5